services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # React served via NGINX
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
