services:
  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/app
    - /app/node_modules
    ports:
      - "3000:5173"  # React served via NGINX
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    #Development
    command: ["npm", "run", "dev"]
    # Production
    # command: ["nginx", "-g", "daemon off;"]

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    #Development
    # command: ["npx", "nodemon", "server.js"]
    #Production
    # command: ["node", "server.js"]
